"""Worked examples supplied by RF engineering. Specification section 24 — **OQ-22**.

Everything else in ``tests/domain/`` proves the engine is *self-consistent*: widths survive
translation, rounding goes outward, a round trip returns what it started with. None of it
proves the answers are the ones RF engineering would give. Only a worked example whose
numbers came from outside the codebase can do that.

**The directory is empty, and that is the honest state.** Inventing a plausible example
would go green, look like validation, and check the engine against itself with extra steps
— which is exactly what §26.20 forbids.

This file runs the **arithmetic** half of an example: bandwidth, placement, translation and
the RF/IF conversion. ``test_golden_scenarios.py`` runs the other half — the same file
against the platform, with real master data, real reservations and the three reuse outcomes
the answer names. Both read the same JSON.

The file format, one JSON object per example::

    {
      "name": "FWD Ka-band, 10 Msps",
      "source": "RF engineering, J. Doe, 2026-05-14",   // required
      "direction": "FWD",

      // The ceiling, and the sub-range actually assigned to the Beam (A-24).
      "payload_path_window": {
        "uplink": [29000000000, 29500000000], "uplink_polarization": "RHCP",
        "downlink": [19000000000, 19500000000], "downlink_polarization": "RHCP"
      },
      "beam_spectrum_assignment": {
        "uplink": [29100000000, 29200000000], "downlink": [19100000000, 19200000000],
        "effective_from": "2026-01-01T00:00:00Z", "effective_until": null
      },
      "equipment": {
        "conversion_method": "LO_PLUS_IF", "sideband": "LOW_SIDE",
        "lo_hz": 28050000000, "if_min_hz": 950000000, "if_max_hz": 1950000000
      },
      "validity": {"valid_from": "2026-06-01T00:00:00Z", "valid_until": null},

      // The requested allocation.
      "symbol_rate_sps": 10000000,
      "rolloff": "0.35",
      "uplink_centre_hz": 29145000000,
      "guard": {"mode": "FIXED", "left_hz": 1000000, "right_hz": 1000000},
      "translation": {"method": "OFFSET_SUBTRACT", "constant_hz": 10000000000},

      "expect": {
        "occupied_bandwidth_hz": 13500000,
        "uplink_occupied": [29138250000, 29151750000],
        "uplink_allocated": [29137250000, 29152750000],
        "downlink_occupied": [19138250000, 19151750000],
        "downlink_allocated": [19137250000, 19152750000],
        "if_occupied": [1088250000, 1101750000],
        "free_capacity": {"leg": "HUB_UPLINK", "gaps": [[...]], "total_free_hz": 0},
        "scenarios": [ ... see test_golden_scenarios.py ... ]
      }
    }

``source`` is required and is not ceremony: an example whose provenance nobody can state is
indistinguishable from one somebody made up, which is the thing this directory exists to
avoid. The **OQ-22** answer goes further — the numbers must be *"calculated independently by
an RF engineer"* from a currently operational Forward Satnet Path, never generated by this
implementation (**A-29**).
"""

from __future__ import annotations

import json
import os
from decimal import Decimal
from pathlib import Path

import pytest

from calculations import bandwidth, conversion, guards
from calculations.ranges import FrequencyRange
from calculations.translation import TranslationMethod, TranslationSpec
from calculations.types import BandwidthRequest, GuardMode, GuardPolicySpec, GuardSource

GOLDEN_DIR = Path(__file__).parent / "golden"

#: Set by the Phase 9 pipeline. Until then the absence is a skip; from then it is a failure.
REQUIRE_FLAG = "VSAT_REQUIRE_GOLDEN_EXAMPLES"

#: What a scenario may assert, and what each one exists to prove. The three the OQ-22 answer
#: names, plus the validity case it names alongside them.
SCENARIO_KINDS = {
    "REJECT_SHARED_PAYLOAD_INPUT": (
        "An overlapping allocation through another Hub, Beam or redundant ground site, on "
        "the same payload input and polarization, is refused."
    ),
    "ACCEPT_INDEPENDENT_POLARIZATION": (
        "An allocation on a polarization whose RF chains are independently implemented may "
        "be accepted."
    ),
    "REJECT_OUTSIDE_ASSIGNMENT": ("An allocation outside the Beam Spectrum Assignment is refused."),
    "REJECT_OUTSIDE_VALIDITY": (
        "An allocation outside the Beam Spectrum Assignment's validity period is refused."
    ),
}

#: The sections **A-29** requires an approved example to state. Listed here rather than
#: checked ad hoc so that "the example is incomplete" is one failure with one message.
REQUIRED_SECTIONS = (
    "payload_path_window",
    "beam_spectrum_assignment",
    "equipment",
    "validity",
    "translation",
)


def example_files() -> list[Path]:
    return sorted(GOLDEN_DIR.glob("*.json"))


def load(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _required() -> bool:
    return os.environ.get(REQUIRE_FLAG, "").strip().lower() in {"1", "true", "yes", "on"}


# ---------------------------------------------------------------------------
# The gate
# ---------------------------------------------------------------------------
def test_the_golden_directory_exists_and_is_documented():
    """The harness is wired up before the data arrives, so adding an example is dropping in
    a file rather than writing a test."""
    assert GOLDEN_DIR.is_dir()
    assert (GOLDEN_DIR / "README.md").exists()


def test_golden_examples_are_present_when_they_are_required():
    """OQ-22's deadline, expressed as a test.

    While the flag is unset this reports the gap and moves on. Phase 9 sets it, and from
    that point an empty directory fails the build. That is what stops "we will add them
    later" from quietly becoming "we shipped without them".
    """
    if example_files():
        return

    message = (
        "No golden worked examples in tests/domain/golden/. The engine is only proven "
        "self-consistent, never correct against RF engineering's own figures (section 24, "
        "OQ-22)."
    )
    if _required():
        pytest.fail(message + f" {REQUIRE_FLAG} is set, so this is now a failure.")
    pytest.skip(message + f" Set {REQUIRE_FLAG}=1 to make this a failure.")


# ---------------------------------------------------------------------------
# The examples themselves
# ---------------------------------------------------------------------------
@pytest.mark.parametrize("path", example_files(), ids=lambda p: p.stem)
def test_a_golden_example_states_everything_the_answer_requires(path: Path):
    """**A-29**: a file that states only the arithmetic does not close OQ-22.

    The answer is explicit about what the approved example contains, and about what the three
    outcomes are for. An example missing the reuse scenarios would pass every other test here
    and prove nothing about the thing OQ-25 changed, so the completeness check is a test
    rather than a note in a README.
    """
    example = load(path)

    assert example.get("source"), (
        f"{path.name} has no 'source'. An example whose provenance nobody can state is "
        f"indistinguishable from one somebody made up."
    )
    missing = [section for section in REQUIRED_SECTIONS if not example.get(section)]
    assert not missing, (
        f"{path.name} does not state {missing}. OQ-22's answer requires the Payload Path "
        f"Window, the Beam Spectrum Assignment, the RF/IF conversion rule, the equipment "
        f"limits and the validity periods."
    )

    expected = example.get("expect", {})
    assert expected.get("free_capacity"), (
        f"{path.name} states no expected free-capacity result, which the answer names explicitly."
    )

    kinds = {scenario.get("kind") for scenario in expected.get("scenarios", [])}
    unknown = kinds - set(SCENARIO_KINDS)
    assert not unknown, f"{path.name} uses unknown scenario kinds {sorted(unknown)}."
    for required_kind in (
        "REJECT_SHARED_PAYLOAD_INPUT",
        "ACCEPT_INDEPENDENT_POLARIZATION",
        "REJECT_OUTSIDE_ASSIGNMENT",
    ):
        assert required_kind in kinds, (
            f"{path.name} has no {required_kind} scenario. {SCENARIO_KINDS[required_kind]}"
        )


@pytest.mark.parametrize("path", example_files(), ids=lambda p: p.stem)
def test_a_golden_example_matches_the_engine(path: Path):
    """Run one supplied example through the engine and compare every stated value."""
    example = load(path)
    placement = _run(example)
    expected = example["expect"]

    if "occupied_bandwidth_hz" in expected:
        assert placement.uplink.occupied_bandwidth_hz == expected["occupied_bandwidth_hz"]
    for key, actual in (
        ("uplink_occupied", placement.uplink.occupied),
        ("uplink_allocated", placement.uplink.allocated),
        ("downlink_occupied", placement.downlink.occupied),
        ("downlink_allocated", placement.downlink.allocated),
    ):
        if key in expected and expected[key] != [None, None]:
            assert actual == FrequencyRange(*expected[key]), key


@pytest.mark.parametrize("path", example_files(), ids=lambda p: p.stem)
def test_a_golden_example_matches_the_stated_if(path: Path):
    """The hub LO and IF limits, which the answer asks the example to state. §13.5.

    Separate from the placement test because it fails for a different reason: an IF mismatch
    means the conversion rule disagrees with the equipment, not that the bandwidth arithmetic
    is wrong, and one failure should not be able to hide the other.
    """
    example = load(path)
    expected = example.get("expect", {}).get("if_occupied")
    if not expected or expected == [None, None]:
        pytest.skip(f"{path.name} states no expected IF range.")

    placement = _run(example)
    profile = _equipment(example)
    computed = conversion.to_intermediate(placement.uplink.occupied, profile)

    assert computed == FrequencyRange(*expected)
    assert profile.if_limits.contains(computed), (
        f"{path.name} expects an IF outside the equipment's own limits, which the platform "
        f"would refuse."
    )


def _run(example: dict):
    """Build the engine inputs from an example file."""
    translation = TranslationSpec(
        method=TranslationMethod(example["translation"]["method"]),
        constant_hz=example["translation"]["constant_hz"],
        spectral_inversion=example["translation"].get("spectral_inversion", False),
    )
    request = BandwidthRequest(
        rolloff=Decimal(example["rolloff"]),
        symbol_rate_sps=example.get("symbol_rate_sps"),
        occupied_bandwidth_hz=example.get("occupied_bandwidth_hz"),
    )
    _, occupied_bw = bandwidth.resolve_request(request)
    return bandwidth.place_both_sides(
        request=request,
        centre_hz=example["uplink_centre_hz"],
        guards=guards.resolve(_guard_policy(example.get("guard")), occupied_bw),
        translation=translation,
    )


def _equipment(example: dict) -> conversion.EquipmentProfileSpec:
    """The hub profile the example states, as the engine's own value type."""
    stated = example["equipment"]
    window = example["payload_path_window"]["uplink"]
    return conversion.EquipmentProfileSpec(
        code="golden example",
        method=conversion.ConversionMethod(stated["conversion_method"]),
        sideband=conversion.Sideband(stated["sideband"]),
        lo_hz=stated["lo_hz"],
        rf_limits=FrequencyRange(*window),
        if_limits=FrequencyRange(stated["if_min_hz"], stated["if_max_hz"]),
    )


def _guard_policy(guard: dict | None) -> GuardPolicySpec | None:
    if not guard:
        return None
    return GuardPolicySpec(
        mode=GuardMode(guard["mode"]),
        source=GuardSource.OVERRIDE,
        label="golden example",
        fixed_left_hz=guard.get("left_hz"),
        fixed_right_hz=guard.get("right_hz"),
        # Tested on the value, not on the key. A FIXED-mode example written from the S0
        # intake template carries `"percent_left": null` — the engineer left the percentage
        # columns blank, which is the correct answer for that mode — and keying on presence
        # would try to build a Decimal from None and crash on a well-formed file.
        percent_left=_optional_decimal(guard.get("percent_left")),
        percent_right=_optional_decimal(guard.get("percent_right")),
    )


def _optional_decimal(value: str | int | None) -> Decimal | None:
    return None if value is None else Decimal(str(value))
