# Generated by Django 5.2.16 on 2026-08-03 12:14

import django.core.validators
import django.db.models.deletion
import specifications.registry
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SpecificationCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Specification category",
                "verbose_name_plural": "Specification categories",
                "db_table": "specification_category",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SpecificationDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Stable internal code referenced by application logic. Cannot be changed once the code is used by the calculation engine.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "is_system_managed",
                    models.BooleanField(
                        default=False,
                        help_text="Set for codes the application refers to by name. The code of such a row is read-only; all of its other attributes remain editable.",
                    ),
                ),
                ("display_name", models.CharField(max_length=200)),
                ("short_name", models.CharField(blank=True, max_length=60)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Full explanation shown in the information popover.",
                    ),
                ),
                (
                    "help_text",
                    models.TextField(
                        blank=True,
                        help_text="Guidance shown beside the field in forms.",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="Unit as presented to the user, for example MHz or symbols/second.",
                        max_length=40,
                    ),
                ),
                (
                    "display_precision",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Decimal places used when the value is displayed.",
                        validators=[django.core.validators.MaxValueValidator(12)],
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("INTEGER_HZ", "INTEGER_HZ"),
                            ("INTEGER_SPS", "INTEGER_SPS"),
                            ("DECIMAL", "DECIMAL"),
                            ("TEXT", "TEXT"),
                            ("BOOLEAN", "BOOLEAN"),
                            ("TIMESTAMP", "TIMESTAMP"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "direction_applicability",
                    models.CharField(
                        choices=[
                            ("FWD", "FWD"),
                            ("RTN", "RTN"),
                            ("BOTH", "BOTH"),
                            ("NA", "NOT_APPLICABLE"),
                        ],
                        default=specifications.registry.DirectionApplicability["BOTH"],
                        max_length=4,
                    ),
                ),
                (
                    "is_calculated",
                    models.BooleanField(
                        default=False,
                        help_text="Derived by the calculation engine and read-only for operators (specification section 26.16).",
                    ),
                ),
                (
                    "calculation_note",
                    models.TextField(
                        blank=True,
                        help_text="Formula or explanation of how the value is derived.",
                    ),
                ),
                (
                    "source_reference",
                    models.TextField(
                        blank=True,
                        help_text="Engineering document or standard this definition comes from.",
                    ),
                ),
                ("visible_in_tables", models.BooleanField(default=True)),
                ("visible_in_forms", models.BooleanField(default=False)),
                ("visible_in_detail", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
                ("record_version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="specifications",
                        to="specifications.specificationcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Specification definition",
                "verbose_name_plural": "Specification definitions",
                "db_table": "specification_definition",
                "ordering": ["category__display_order", "display_order", "code"],
                "indexes": [
                    models.Index(
                        fields=["category", "display_order"],
                        name="spec_category_order_idx",
                    ),
                    models.Index(
                        condition=models.Q(
                            ("is_active", True), ("visible_in_tables", True)
                        ),
                        fields=["display_order"],
                        name="spec_table_visible_idx",
                    ),
                ],
            },
        ),
    ]
