# Generated by Django 5.2.16 on 2026-08-04 22:53

import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("beams", "0004_beam_effective_from_beam_effective_until_and_more"),
        (
            "inventory",
            "0004_spectrumresource_frequencywindow_uq_window_id_edges_and_more",
        ),
        ("satnets", "0002_satnet_hub_gateway_composite_key"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SatnetPath",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("record_version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                (
                    "direction",
                    models.CharField(
                        choices=[("FWD", "Forward"), ("RTN", "Return")], max_length=3
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PLANNED", "Planned"),
                            ("PENDING_APPROVAL", "Pending approval"),
                            ("ON_AIR", "On air"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("RETIRED", "Retired"),
                            ("IMPORT_REVIEW", "Awaiting import review"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("change_reason", models.TextField(blank=True)),
                (
                    "revision_group",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                ("revision_number", models.PositiveIntegerField(default=1)),
                (
                    "input_mode",
                    models.CharField(
                        choices=[
                            ("OCCUPIED_BW", "Occupied bandwidth"),
                            ("SYMBOL_RATE", "Symbol rate"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "input_value",
                    models.BigIntegerField(
                        help_text="Occupied bandwidth in Hz, or symbol rate in symbols per second."
                    ),
                ),
                ("rolloff", models.DecimalField(decimal_places=3, max_digits=4)),
                ("guard_left_hz", models.BigIntegerField(default=0)),
                ("guard_right_hz", models.BigIntegerField(default=0)),
                ("symbol_rate_sps", models.BigIntegerField(blank=True, null=True)),
                ("occupied_bw_hz", models.BigIntegerField()),
                ("allocated_bw_hz", models.BigIntegerField()),
                (
                    "canonical_leg",
                    models.CharField(
                        choices=[
                            ("HUB_UPLINK", "Hub uplink"),
                            ("REMOTE_DOWNLINK", "Remote downlink"),
                            ("REMOTE_UPLINK", "Remote uplink"),
                            ("HUB_DOWNLINK", "Hub downlink"),
                        ],
                        max_length=16,
                    ),
                ),
                ("canonical_center_hz", models.BigIntegerField()),
                ("canonical_occupied_start_hz", models.BigIntegerField()),
                ("canonical_occupied_end_hz", models.BigIntegerField()),
                ("canonical_allocated_start_hz", models.BigIntegerField()),
                ("canonical_allocated_end_hz", models.BigIntegerField()),
                (
                    "canonical_polarization",
                    models.CharField(
                        choices=[
                            ("RHCP", "Right-hand circular"),
                            ("LHCP", "Left-hand circular"),
                            ("H", "Linear horizontal"),
                            ("V", "Linear vertical"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "translated_leg",
                    models.CharField(
                        choices=[
                            ("HUB_UPLINK", "Hub uplink"),
                            ("REMOTE_DOWNLINK", "Remote downlink"),
                            ("REMOTE_UPLINK", "Remote uplink"),
                            ("HUB_DOWNLINK", "Hub downlink"),
                        ],
                        max_length=16,
                    ),
                ),
                ("translated_center_hz", models.BigIntegerField()),
                ("translated_occupied_start_hz", models.BigIntegerField()),
                ("translated_occupied_end_hz", models.BigIntegerField()),
                ("translated_allocated_start_hz", models.BigIntegerField()),
                ("translated_allocated_end_hz", models.BigIntegerField()),
                (
                    "translated_polarization",
                    models.CharField(
                        choices=[
                            ("RHCP", "Right-hand circular"),
                            ("LHCP", "Left-hand circular"),
                            ("H", "Linear horizontal"),
                            ("V", "Linear vertical"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "canonical_occupied_rf",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Func(
                            models.F("canonical_occupied_start_hz"),
                            models.F("canonical_occupied_end_hz"),
                            models.Value("[)"),
                            function="int8range",
                            output_field=django.contrib.postgres.fields.ranges.BigIntegerRangeField(),
                        ),
                        output_field=django.contrib.postgres.fields.ranges.BigIntegerRangeField(),
                    ),
                ),
                (
                    "canonical_allocated_rf",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Func(
                            models.F("canonical_allocated_start_hz"),
                            models.F("canonical_allocated_end_hz"),
                            models.Value("[)"),
                            function="int8range",
                            output_field=django.contrib.postgres.fields.ranges.BigIntegerRangeField(),
                        ),
                        output_field=django.contrib.postgres.fields.ranges.BigIntegerRangeField(),
                    ),
                ),
                (
                    "translated_occupied_rf",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Func(
                            models.F("translated_occupied_start_hz"),
                            models.F("translated_occupied_end_hz"),
                            models.Value("[)"),
                            function="int8range",
                            output_field=django.contrib.postgres.fields.ranges.BigIntegerRangeField(),
                        ),
                        output_field=django.contrib.postgres.fields.ranges.BigIntegerRangeField(),
                    ),
                ),
                (
                    "translated_allocated_rf",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Func(
                            models.F("translated_allocated_start_hz"),
                            models.F("translated_allocated_end_hz"),
                            models.Value("[)"),
                            function="int8range",
                            output_field=django.contrib.postgres.fields.ranges.BigIntegerRangeField(),
                        ),
                        output_field=django.contrib.postgres.fields.ranges.BigIntegerRangeField(),
                    ),
                ),
                ("lo_hz", models.BigIntegerField(blank=True, null=True)),
                ("if_start_hz", models.BigIntegerField(blank=True, null=True)),
                ("if_center_hz", models.BigIntegerField(blank=True, null=True)),
                ("if_end_hz", models.BigIntegerField(blank=True, null=True)),
                ("gw_id", models.CharField(blank=True, max_length=100)),
                ("decimator", models.CharField(blank=True, max_length=100)),
                (
                    "beam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paths",
                        to="beams.beam",
                    ),
                ),
                (
                    "canonical_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paths_as_canonical",
                        to="beams.beamspectrumassignment",
                    ),
                ),
                (
                    "canonical_window",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paths_as_canonical",
                        to="inventory.frequencywindow",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipment_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="satnet_paths",
                        to="inventory.equipmentprofile",
                    ),
                ),
                (
                    "guard_policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="satnet_paths",
                        to="inventory.guardpolicy",
                    ),
                ),
                (
                    "satnet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paths",
                        to="satnets.satnet",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="satnet_paths.satnetpath",
                    ),
                ),
                (
                    "translated_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paths_as_translated",
                        to="beams.beamspectrumassignment",
                    ),
                ),
                (
                    "translated_window",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paths_as_translated",
                        to="inventory.frequencywindow",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "satnet_path",
                "ordering": ["satnet__code", "code", "-revision_number"],
                "permissions": [
                    ("manage_satnet_paths", "Can create and change Satnet Paths")
                ],
                "default_permissions": ("view",),
                "indexes": [
                    models.Index(
                        fields=["satnet", "status"], name="path_satnet_status_idx"
                    ),
                    models.Index(
                        fields=["revision_group", "revision_number"],
                        name="path_revision_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("satnet", "code", "revision_number"),
                        name="uq_path_satnet_code_revision",
                    ),
                    models.UniqueConstraint(
                        fields=("revision_group", "revision_number"),
                        name="uq_path_revision",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("symbol_rate_sps__isnull", True),
                            ("symbol_rate_sps__gt", 0),
                            _connector="OR",
                        ),
                        name="ck_path_symbol_rate",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("rolloff__gte", 0), ("rolloff__lte", 1)),
                        name="ck_path_rolloff",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("guard_left_hz__gte", 0), ("guard_right_hz__gte", 0)
                        ),
                        name="ck_path_guards",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("occupied_bw_hz__gt", 0),
                            ("allocated_bw_hz__gte", models.F("occupied_bw_hz")),
                        ),
                        name="ck_path_bw_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "canonical_center_hz__gte",
                                models.F("canonical_occupied_start_hz"),
                            ),
                            (
                                "canonical_center_hz__lt",
                                models.F("canonical_occupied_end_hz"),
                            ),
                            (
                                "translated_center_hz__gte",
                                models.F("translated_occupied_start_hz"),
                            ),
                            (
                                "translated_center_hz__lt",
                                models.F("translated_occupied_end_hz"),
                            ),
                        ),
                        name="ck_path_center_in_occupied",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "canonical_occupied_start_hz__gte",
                                models.F("canonical_allocated_start_hz"),
                            ),
                            (
                                "canonical_occupied_end_hz__lte",
                                models.F("canonical_allocated_end_hz"),
                            ),
                            (
                                "translated_occupied_start_hz__gte",
                                models.F("translated_allocated_start_hz"),
                            ),
                            (
                                "translated_occupied_end_hz__lte",
                                models.F("translated_allocated_end_hz"),
                            ),
                        ),
                        name="ck_path_occ_in_alloc",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("valid_until__isnull", True),
                            ("valid_until__gt", models.F("valid_from")),
                            _connector="OR",
                        ),
                        name="ck_path_validity",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("canonical_leg", "HUB_UPLINK"),
                                ("direction", "FWD"),
                                ("translated_leg", "REMOTE_DOWNLINK"),
                            ),
                            models.Q(
                                ("canonical_leg", "REMOTE_UPLINK"),
                                ("direction", "RTN"),
                                ("translated_leg", "HUB_DOWNLINK"),
                            ),
                            _connector="OR",
                        ),
                        name="ck_path_legs",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("input_value__gt", 0)),
                        name="ck_path_input_value",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("if_start_hz__isnull", True),
                            models.Q(
                                ("if_start_hz__gte", 0),
                                ("if_start_hz__lt", models.F("if_end_hz")),
                            ),
                            _connector="OR",
                        ),
                        name="ck_path_if",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("revision_number", 1), ("supersedes__isnull", True)
                            ),
                            models.Q(
                                ("revision_number__gt", 1),
                                ("supersedes__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="ck_path_revision",
                    ),
                ],
            },
        ),
    ]
