# Generated by Django 5.2.16 on 2026-08-05 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_decimators"),
        ("satnet_paths", "0002_path_satnet_beam_composite_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="satnetpath",
            name="decimator",
        ),
        migrations.RemoveField(
            model_name="satnetpath",
            name="gw_id",
        ),
        migrations.AddField(
            model_name="satnetpath",
            name="decimator_assignment",
            field=models.ForeignKey(
                blank=True,
                help_text="The Decimator configuration this Path consumes. Several Paths may share one.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="satnet_paths",
                to="inventory.decimatorassignment",
            ),
        ),
        migrations.AddField(
            model_name="satnetpath",
            name="gateway",
            field=models.ForeignKey(
                blank=True,
                help_text="The Gateway this Path runs through. A shared reference, not a reservation.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="satnet_paths",
                to="inventory.gateway",
                verbose_name="GW ID",
            ),
        ),
    ]
