# Generated by Django 5.2.16 on 2026-08-05 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("satnet_paths", "0003_controlled_hardware_references"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="satnetpath",
            options={
                "default_permissions": ("view",),
                "ordering": ["satnet__code", "code", "-revision_number"],
                "permissions": [
                    ("manage_satnet_paths", "Can create and change Satnet Paths"),
                    ("plan_satnetpath", "Can move a Satnet Path from draft to planned"),
                    ("submit_satnetpath", "Can submit a Satnet Path for approval"),
                    ("approve_satnetpath", "Can approve a Satnet Path onto air"),
                    ("reject_satnetpath", "Can reject a Satnet Path back to planned"),
                    (
                        "suspend_satnetpath",
                        "Can suspend and resume an on-air Satnet Path",
                    ),
                    ("retire_satnetpath", "Can retire a Satnet Path"),
                    ("cancel_satnetpath", "Can cancel a draft or planned Satnet Path"),
                    ("revise_satnetpath", "Can create a new revision of a Satnet Path"),
                ],
            },
        ),
    ]
