# Generated by Django 5.2.16 on 2026-08-05 13:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("page", models.CharField(default="satnet_paths", max_length=50)),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("columns", models.JSONField(blank=True, default=list)),
                ("sort", models.CharField(blank=True, max_length=60)),
                (
                    "is_shared",
                    models.BooleanField(
                        default=False,
                        help_text="Offer this view to everybody. They still see only what their scope allows.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "saved_view",
                "ordering": ["name"],
                "default_permissions": ("view", "add", "change", "delete"),
                "indexes": [
                    models.Index(
                        fields=["page", "is_shared"], name="saved_view_shared_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "page", "name"),
                        name="uq_saved_view_owner_page_name",
                    )
                ],
            },
        ),
    ]
