# Generated by Django 5.2.16 on 2026-08-03 14:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # btree_gist is what lets a GiST index mix uuid equality with range
        # overlap. Without this dependency the graph may run inventory before the
        # extension exists — which is exactly what happens on a fresh database.
        ("operations", "0001_extensions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Band",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("record_version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "rf_min_hz",
                    models.BigIntegerField(help_text="Informative lower bound, in Hz."),
                ),
                (
                    "rf_max_hz",
                    models.BigIntegerField(help_text="Informative upper bound, in Hz."),
                ),
                (
                    "default_display_unit",
                    models.CharField(default="MHz", max_length=20),
                ),
                (
                    "tuning_raster_hz",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Minimum centre-frequency step, in Hz. Leave empty when unconfirmed (OQ-31).",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "band",
                "ordering": ["code"],
                "default_permissions": ("view",),
            },
        ),
        migrations.CreateModel(
            name="BandPolarization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "polarization",
                    models.CharField(
                        choices=[
                            ("RHCP", "Right-hand circular"),
                            ("LHCP", "Left-hand circular"),
                            ("H", "Linear horizontal"),
                            ("V", "Linear vertical"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "band",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allowed_polarizations",
                        to="inventory.band",
                    ),
                ),
            ],
            options={
                "db_table": "band_polarization",
                "ordering": ["polarization"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Gateway",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("record_version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "time_zone",
                    models.CharField(
                        blank=True,
                        help_text="IANA time zone name, for example Europe/Istanbul.",
                        max_length=64,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                ("technical_notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "gateway",
                "ordering": ["code"],
                "default_permissions": ("view",),
            },
        ),
        migrations.CreateModel(
            name="Hub",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("record_version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=200)),
                ("site", models.CharField(blank=True, max_length=200)),
                (
                    "platform",
                    models.CharField(
                        blank=True, help_text="Hub system or platform.", max_length=200
                    ),
                ),
                ("vendor", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                ("technical_notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "gateway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hubs",
                        to="inventory.gateway",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hub",
                "ordering": ["gateway__code", "code"],
                "default_permissions": ("view",),
            },
        ),
        migrations.CreateModel(
            name="EquipmentProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("record_version", models.PositiveIntegerField(default=1)),
                ("effective_from", models.DateTimeField()),
                (
                    "effective_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leave empty for an open-ended record.",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("BUC", "Block up-converter"),
                            ("BDC", "Block down-converter"),
                            ("LNB", "Low-noise block down-converter"),
                            ("OTHER", "Other"),
                        ],
                        max_length=6,
                    ),
                ),
                ("vendor", models.CharField(blank=True, max_length=200)),
                ("model", models.CharField(blank=True, max_length=200)),
                ("rf_min_hz", models.BigIntegerField()),
                ("rf_max_hz", models.BigIntegerField()),
                ("if_min_hz", models.BigIntegerField()),
                ("if_max_hz", models.BigIntegerField()),
                (
                    "lo_hz",
                    models.BigIntegerField(
                        help_text="Local oscillator frequency, in Hz."
                    ),
                ),
                (
                    "conversion_method",
                    models.CharField(
                        choices=[
                            ("LO_PLUS_IF", "RF = LO + IF"),
                            ("LO_MINUS_IF", "RF = LO - IF"),
                            ("FIXED_OFFSET", "RF = IF + fixed offset"),
                        ],
                        max_length=14,
                    ),
                ),
                (
                    "sideband",
                    models.CharField(
                        choices=[
                            ("LOW_SIDE", "Low-side injection (LO below RF)"),
                            ("HIGH_SIDE", "High-side injection (LO above RF)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("spectral_inversion", models.BooleanField(default=False)),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Lower sorts first when several profiles are valid.",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("engineering_reference", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                (
                    "version_group",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Shared by every version of the same logical profile.",
                    ),
                ),
                ("version_number", models.PositiveIntegerField(default=1)),
                (
                    "band",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="equipment_profiles",
                        to="inventory.band",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="inventory.equipmentprofile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "gateway",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="equipment_profiles",
                        to="inventory.gateway",
                    ),
                ),
                (
                    "hub",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="equipment_profiles",
                        to="inventory.hub",
                    ),
                ),
            ],
            options={
                "db_table": "equipment_profile",
                "ordering": ["code", "-version_number"],
                "default_permissions": ("view",),
            },
        ),
        migrations.CreateModel(
            name="Satellite",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("record_version", models.PositiveIntegerField(default=1)),
                ("effective_from", models.DateTimeField()),
                (
                    "effective_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leave empty for an open-ended record.",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("operator", models.CharField(blank=True, max_length=200)),
                (
                    "orbital_position",
                    models.CharField(
                        blank=True,
                        help_text="For example 42.0E for a geostationary satellite.",
                        max_length=50,
                    ),
                ),
                (
                    "orbit_type",
                    models.CharField(
                        choices=[
                            ("GEO", "Geostationary"),
                            ("MEO", "Medium Earth orbit"),
                            ("LEO", "Low Earth orbit"),
                        ],
                        max_length=3,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                (
                    "engineering_reference",
                    models.TextField(
                        blank=True,
                        help_text="Engineering or reference document for this satellite.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "satellite",
                "ordering": ["code"],
                "permissions": [
                    (
                        "manage_inventory",
                        "Can create, edit and deactivate inventory master data",
                    )
                ],
                "default_permissions": ("view",),
            },
        ),
        migrations.AddConstraint(
            model_name="band",
            constraint=models.CheckConstraint(
                condition=models.Q(("rf_min_hz__lt", models.F("rf_max_hz"))),
                name="ck_band_rf_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="band",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("tuning_raster_hz__isnull", True),
                    ("tuning_raster_hz__gt", 0),
                    _connector="OR",
                ),
                name="ck_band_tuning_raster_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="bandpolarization",
            constraint=models.UniqueConstraint(
                fields=("band", "polarization"), name="uq_band_polarization"
            ),
        ),
        migrations.AddConstraint(
            model_name="gateway",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("latitude__isnull", True),
                    models.Q(("latitude__gte", -90), ("latitude__lte", 90)),
                    _connector="OR",
                ),
                name="ck_gateway_latitude_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="gateway",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("longitude__isnull", True),
                    models.Q(("longitude__gte", -180), ("longitude__lte", 180)),
                    _connector="OR",
                ),
                name="ck_gateway_longitude_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="hub",
            constraint=models.UniqueConstraint(
                fields=("gateway", "code"), name="uq_hub_gateway_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="hub",
            constraint=models.UniqueConstraint(
                fields=("id", "gateway"), name="uq_hub_id_gateway"
            ),
        ),
        migrations.AddIndex(
            model_name="equipmentprofile",
            index=models.Index(
                condition=models.Q(("is_active", True)),
                fields=["band", "type", "priority"],
                name="equipment_matching_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="equipmentprofile",
            constraint=models.UniqueConstraint(
                fields=("code", "version_number"), name="uq_equipment_code_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="equipmentprofile",
            constraint=models.UniqueConstraint(
                fields=("version_group", "version_number"),
                name="uq_equipment_group_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="equipmentprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("rf_min_hz__lt", models.F("rf_max_hz"))),
                name="ck_equipment_rf_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="equipmentprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("if_min_hz__lt", models.F("if_max_hz"))),
                name="ck_equipment_if_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="equipmentprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("lo_hz__gt", 0)), name="ck_equipment_lo_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="equipmentprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("if_min_hz__gte", 0)),
                name="ck_equipment_if_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="equipmentprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_until__isnull", True),
                    ("effective_until__gt", models.F("effective_from")),
                    _connector="OR",
                ),
                name="ck_equipment_effective_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="equipmentprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("conversion_method", "LO_PLUS_IF"), ("sideband", "LOW_SIDE")
                    ),
                    models.Q(
                        ("conversion_method", "LO_MINUS_IF"), ("sideband", "HIGH_SIDE")
                    ),
                    ("conversion_method", "FIXED_OFFSET"),
                    _connector="OR",
                ),
                name="ck_equipment_conversion_sideband",
            ),
        ),
        migrations.AddConstraint(
            model_name="satellite",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_until__isnull", True),
                    ("effective_until__gt", models.F("effective_from")),
                    _connector="OR",
                ),
                name="ck_satellite_effective_period",
            ),
        ),
    ]
