# Generated by Django 5.2.16 on 2026-08-03 18:51

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # btree_gist is what lets a GiST index mix uuid equality with range
        # overlap. Without this dependency the graph may run inventory before the
        # extension exists — which is exactly what happens on a fresh database.
        ("operations", "0001_extensions"),
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FrequencyWindow",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("record_version", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("effective_from", models.DateTimeField()),
                (
                    "effective_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leave empty for an open-ended record.",
                        null=True,
                    ),
                ),
                (
                    "version_group",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Shared by every version of the same logical record.",
                    ),
                ),
                ("version_number", models.PositiveIntegerField(default=1)),
                (
                    "effective_period",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Func(
                            models.F("effective_from"),
                            models.F("effective_until"),
                            models.Value("[)"),
                            function="tstzrange",
                            output_field=django.contrib.postgres.fields.ranges.DateTimeRangeField(),
                        ),
                        output_field=django.contrib.postgres.fields.ranges.DateTimeRangeField(),
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=200)),
                (
                    "side",
                    models.CharField(
                        choices=[
                            ("HUB_UPLINK", "Hub uplink"),
                            ("REMOTE_DOWNLINK", "Remote downlink"),
                            ("REMOTE_UPLINK", "Remote uplink"),
                            ("HUB_DOWNLINK", "Hub downlink"),
                        ],
                        help_text="Which leg of the payload chain this window covers.",
                        max_length=16,
                    ),
                ),
                (
                    "polarization",
                    models.CharField(
                        choices=[
                            ("RHCP", "Right-hand circular"),
                            ("LHCP", "Left-hand circular"),
                            ("H", "Linear horizontal"),
                            ("V", "Linear vertical"),
                        ],
                        max_length=4,
                    ),
                ),
                ("rf_start_hz", models.BigIntegerField()),
                (
                    "rf_end_hz",
                    models.BigIntegerField(
                        help_text="Exclusive upper edge: the range is [start, end)."
                    ),
                ),
                (
                    "min_edge_guard_hz",
                    models.BigIntegerField(
                        default=0,
                        help_text="Minimum separation from either edge of the window.",
                    ),
                ),
                ("source_reference", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "db_table": "frequency_window",
                "ordering": ["satellite__code", "side", "rf_start_hz"],
                "default_permissions": ("view",),
            },
        ),
        migrations.CreateModel(
            name="GuardPolicy",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("record_version", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("FIXED", "Fixed width"),
                            ("PERCENT_OF_OCCUPIED", "Percentage of occupied bandwidth"),
                            (
                                "MAX_OF_FIXED_AND_PERCENT",
                                "Greater of fixed and percentage",
                            ),
                        ],
                        max_length=28,
                    ),
                ),
                ("fixed_left_hz", models.BigIntegerField(blank=True, null=True)),
                ("fixed_right_hz", models.BigIntegerField(blank=True, null=True)),
                (
                    "percent_left",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "percent_right",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Guard policies",
                "db_table": "guard_policy",
                "ordering": ["code"],
                "default_permissions": ("view",),
            },
        ),
        migrations.CreateModel(
            name="PayloadPath",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("record_version", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("effective_from", models.DateTimeField()),
                (
                    "effective_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leave empty for an open-ended record.",
                        null=True,
                    ),
                ),
                (
                    "version_group",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Shared by every version of the same logical record.",
                    ),
                ),
                ("version_number", models.PositiveIntegerField(default=1)),
                (
                    "effective_period",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Func(
                            models.F("effective_from"),
                            models.F("effective_until"),
                            models.Value("[)"),
                            function="tstzrange",
                            output_field=django.contrib.postgres.fields.ranges.DateTimeRangeField(),
                        ),
                        output_field=django.contrib.postgres.fields.ranges.DateTimeRangeField(),
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=200)),
                (
                    "direction",
                    models.CharField(
                        choices=[("FWD", "Forward"), ("RTN", "Return")], max_length=3
                    ),
                ),
                (
                    "uplink_window_side",
                    models.CharField(
                        choices=[
                            ("HUB_UPLINK", "Hub uplink"),
                            ("REMOTE_DOWNLINK", "Remote downlink"),
                            ("REMOTE_UPLINK", "Remote uplink"),
                            ("HUB_DOWNLINK", "Hub downlink"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "downlink_window_side",
                    models.CharField(
                        choices=[
                            ("HUB_UPLINK", "Hub uplink"),
                            ("REMOTE_DOWNLINK", "Remote downlink"),
                            ("REMOTE_UPLINK", "Remote uplink"),
                            ("HUB_DOWNLINK", "Hub downlink"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "translation_method",
                    models.CharField(
                        choices=[
                            ("OFFSET_ADD", "Downlink = uplink + offset"),
                            ("OFFSET_SUBTRACT", "Downlink = uplink - offset"),
                            ("LO_REFLECT", "Downlink = constant - uplink (inverting)"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "translation_constant_hz",
                    models.BigIntegerField(
                        help_text="Offset for OFFSET_ADD/OFFSET_SUBTRACT, or the reflection constant for LO_REFLECT."
                    ),
                ),
                ("spectral_inversion", models.BooleanField(default=False)),
                ("engineering_reference", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "db_table": "payload_path",
                "ordering": ["satellite__code", "direction", "code"],
                "default_permissions": ("view",),
            },
        ),
        migrations.CreateModel(
            name="PayloadPolarizationMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "uplink_polarization",
                    models.CharField(
                        choices=[
                            ("RHCP", "Right-hand circular"),
                            ("LHCP", "Left-hand circular"),
                            ("H", "Linear horizontal"),
                            ("V", "Linear vertical"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "downlink_polarization",
                    models.CharField(
                        choices=[
                            ("RHCP", "Right-hand circular"),
                            ("LHCP", "Left-hand circular"),
                            ("H", "Linear horizontal"),
                            ("V", "Linear vertical"),
                        ],
                        max_length=4,
                    ),
                ),
            ],
            options={
                "db_table": "payload_polarization_mapping",
                "ordering": ["uplink_polarization", "downlink_polarization"],
                "default_permissions": (),
            },
        ),
        migrations.AddField(
            model_name="equipmentprofile",
            name="effective_period",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Func(
                    models.F("effective_from"),
                    models.F("effective_until"),
                    models.Value("[)"),
                    function="tstzrange",
                    output_field=django.contrib.postgres.fields.ranges.DateTimeRangeField(),
                ),
                output_field=django.contrib.postgres.fields.ranges.DateTimeRangeField(),
            ),
        ),
        migrations.AlterField(
            model_name="equipmentprofile",
            name="supersedes",
            field=models.ForeignKey(
                blank=True,
                help_text="The version this one replaces.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="superseded_by",
                to="inventory.equipmentprofile",
            ),
        ),
        migrations.AlterField(
            model_name="equipmentprofile",
            name="version_group",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Shared by every version of the same logical record.",
            ),
        ),
        migrations.AddConstraint(
            model_name="equipmentprofile",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("is_active", True)),
                expressions=[("version_group", "="), ("effective_period", "&&")],
                name="excl_equipment_version_overlap",
            ),
        ),
        migrations.AddField(
            model_name="frequencywindow",
            name="band",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="frequency_windows",
                to="inventory.band",
            ),
        ),
        migrations.AddField(
            model_name="frequencywindow",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="frequencywindow",
            name="satellite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="frequency_windows",
                to="inventory.satellite",
            ),
        ),
        migrations.AddField(
            model_name="frequencywindow",
            name="supersedes",
            field=models.ForeignKey(
                blank=True,
                help_text="The version this one replaces.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="superseded_by",
                to="inventory.frequencywindow",
            ),
        ),
        migrations.AddField(
            model_name="frequencywindow",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="guardpolicy",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="guardpolicy",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="frequencywindow",
            name="default_guard_policy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="frequency_windows",
                to="inventory.guardpolicy",
            ),
        ),
        migrations.AddField(
            model_name="payloadpath",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payloadpath",
            name="downlink_window",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payload_paths_as_downlink",
                to="inventory.frequencywindow",
            ),
        ),
        migrations.AddField(
            model_name="payloadpath",
            name="satellite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payload_paths",
                to="inventory.satellite",
            ),
        ),
        migrations.AddField(
            model_name="payloadpath",
            name="supersedes",
            field=models.ForeignKey(
                blank=True,
                help_text="The version this one replaces.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="superseded_by",
                to="inventory.payloadpath",
            ),
        ),
        migrations.AddField(
            model_name="payloadpath",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payloadpath",
            name="uplink_window",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payload_paths_as_uplink",
                to="inventory.frequencywindow",
            ),
        ),
        migrations.AddField(
            model_name="payloadpolarizationmapping",
            name="payload_path",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polarization_mappings",
                to="inventory.payloadpath",
            ),
        ),
        migrations.AddConstraint(
            model_name="guardpolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("fixed_left_hz__isnull", True),
                    ("fixed_left_hz__gte", 0),
                    _connector="OR",
                ),
                name="ck_guard_fixed_left_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="guardpolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("fixed_right_hz__isnull", True),
                    ("fixed_right_hz__gte", 0),
                    _connector="OR",
                ),
                name="ck_guard_fixed_right_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="guardpolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("percent_left__isnull", True),
                    ("percent_left__gte", 0),
                    _connector="OR",
                ),
                name="ck_guard_percent_left_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="guardpolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("percent_right__isnull", True),
                    ("percent_right__gte", 0),
                    _connector="OR",
                ),
                name="ck_guard_percent_right_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="guardpolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("fixed_left_hz__isnull", False),
                        ("fixed_right_hz__isnull", False),
                        ("mode", "FIXED"),
                    ),
                    models.Q(
                        ("mode", "PERCENT_OF_OCCUPIED"),
                        ("percent_left__isnull", False),
                        ("percent_right__isnull", False),
                    ),
                    models.Q(
                        ("fixed_left_hz__isnull", False),
                        ("fixed_right_hz__isnull", False),
                        ("mode", "MAX_OF_FIXED_AND_PERCENT"),
                        ("percent_left__isnull", False),
                        ("percent_right__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="ck_guard_mode_has_required_values",
            ),
        ),
        migrations.AddIndex(
            model_name="frequencywindow",
            index=models.Index(
                condition=models.Q(("is_active", True)),
                fields=["satellite", "side", "polarization"],
                name="window_lookup_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="frequencywindow",
            constraint=models.UniqueConstraint(
                fields=("satellite", "code", "version_number"),
                name="uq_window_satellite_code_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="frequencywindow",
            constraint=models.UniqueConstraint(
                fields=("version_group", "version_number"),
                name="uq_window_group_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="frequencywindow",
            constraint=models.UniqueConstraint(
                fields=("id", "side"), name="uq_window_id_side"
            ),
        ),
        migrations.AddConstraint(
            model_name="frequencywindow",
            constraint=models.UniqueConstraint(
                fields=("id", "side", "polarization"),
                name="uq_window_id_side_polarization",
            ),
        ),
        migrations.AddConstraint(
            model_name="frequencywindow",
            constraint=models.CheckConstraint(
                condition=models.Q(("rf_start_hz__lt", models.F("rf_end_hz"))),
                name="ck_window_start_lt_end",
            ),
        ),
        migrations.AddConstraint(
            model_name="frequencywindow",
            constraint=models.CheckConstraint(
                condition=models.Q(("min_edge_guard_hz__gte", 0)),
                name="ck_window_edge_guard_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="frequencywindow",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_until__isnull", True),
                    ("effective_until__gt", models.F("effective_from")),
                    _connector="OR",
                ),
                name="ck_window_effective_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="frequencywindow",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("is_active", True)),
                expressions=[("version_group", "="), ("effective_period", "&&")],
                name="excl_window_version_overlap",
            ),
        ),
        migrations.AddIndex(
            model_name="payloadpath",
            index=models.Index(
                condition=models.Q(("is_active", True)),
                fields=["satellite", "direction"],
                name="path_lookup_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="payloadpath",
            constraint=models.UniqueConstraint(
                fields=("satellite", "code", "version_number"),
                name="uq_path_satellite_code_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="payloadpath",
            constraint=models.UniqueConstraint(
                fields=("version_group", "version_number"), name="uq_path_group_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="payloadpath",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_until__isnull", True),
                    ("effective_until__gt", models.F("effective_from")),
                    _connector="OR",
                ),
                name="ck_path_effective_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="payloadpath",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("direction", "FWD"),
                        ("downlink_window_side", "REMOTE_DOWNLINK"),
                        ("uplink_window_side", "HUB_UPLINK"),
                    ),
                    models.Q(
                        ("direction", "RTN"),
                        ("downlink_window_side", "HUB_DOWNLINK"),
                        ("uplink_window_side", "REMOTE_UPLINK"),
                    ),
                    _connector="OR",
                ),
                name="ck_path_direction_sides",
            ),
        ),
        migrations.AddConstraint(
            model_name="payloadpath",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("uplink_window", models.F("downlink_window")), _negated=True
                ),
                name="ck_path_windows_differ",
            ),
        ),
        migrations.AddConstraint(
            model_name="payloadpath",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("is_active", True)),
                expressions=[("version_group", "="), ("effective_period", "&&")],
                name="excl_path_version_overlap",
            ),
        ),
        migrations.AddConstraint(
            model_name="payloadpolarizationmapping",
            constraint=models.UniqueConstraint(
                fields=("payload_path", "uplink_polarization", "downlink_polarization"),
                name="uq_payload_polarization_mapping",
            ),
        ),
    ]
