# Generated by Django 5.2.16 on 2026-08-04 17:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_payload_path_composite_keys"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SpectrumResource",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("record_version", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("effective_from", models.DateTimeField()),
                (
                    "effective_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leave empty for an open-ended record.",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("PAYLOAD_INPUT", "Shared satellite payload input"),
                            ("RF_CHAIN", "Shared RF chain"),
                            (
                                "BEAM_PLAN",
                                "Approved Beam frequency and polarization plan",
                            ),
                        ],
                        help_text="What kind of thing is shared. Recorded from the approved plan, not inferred.",
                        max_length=20,
                    ),
                ),
                (
                    "leg",
                    models.CharField(
                        choices=[
                            ("HUB_UPLINK", "Hub uplink"),
                            ("REMOTE_DOWNLINK", "Remote downlink"),
                            ("REMOTE_UPLINK", "Remote uplink"),
                            ("HUB_DOWNLINK", "Hub downlink"),
                        ],
                        help_text="Which leg of the payload chain this resource sits on.",
                        max_length=16,
                    ),
                ),
                (
                    "polarization",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RHCP", "Right-hand circular"),
                            ("LHCP", "Left-hand circular"),
                            ("H", "Linear horizontal"),
                            ("V", "Linear vertical"),
                        ],
                        help_text="Leave empty when the RF chains are shared across polarizations.",
                        max_length=4,
                    ),
                ),
                (
                    "source_reference",
                    models.TextField(
                        blank=True,
                        help_text="The approved frequency and polarization plan this resource comes from.",
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "db_table": "spectrum_resource",
                "ordering": ["satellite__code", "leg", "code"],
                "default_permissions": ("view",),
            },
        ),
        migrations.AddConstraint(
            model_name="frequencywindow",
            constraint=models.UniqueConstraint(
                fields=("id", "rf_start_hz", "rf_end_hz"), name="uq_window_id_edges"
            ),
        ),
        migrations.AddField(
            model_name="spectrumresource",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="spectrumresource",
            name="satellite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="spectrum_resources",
                to="inventory.satellite",
            ),
        ),
        migrations.AddField(
            model_name="spectrumresource",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="spectrumresource",
            index=models.Index(
                condition=models.Q(("is_active", True)),
                fields=["satellite", "leg"],
                name="spectrum_resource_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="spectrumresource",
            constraint=models.UniqueConstraint(
                fields=("satellite", "code"), name="uq_spectrum_resource_satellite_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="spectrumresource",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_until__isnull", True),
                    ("effective_until__gt", models.F("effective_from")),
                    _connector="OR",
                ),
                name="ck_spectrum_resource_effective_period",
            ),
        ),
    ]
