# Generated by Django 5.2.16 on 2026-08-05 07:17

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0004_spectrumresource_frequencywindow_uq_window_id_edges_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Decimator",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("record_version", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("technical_notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decimators",
                        to="inventory.hub",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "decimator",
                "ordering": ["hub__code", "code"],
                "default_permissions": ("view",),
            },
        ),
        migrations.CreateModel(
            name="DecimatorAssignment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("record_version", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("effective_from", models.DateTimeField()),
                (
                    "effective_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leave empty for an open-ended record.",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "input_connection",
                    models.CharField(
                        help_text="The input this configuration processes, as named in the hub's own plan.",
                        max_length=100,
                    ),
                ),
                ("processed_start_hz", models.BigIntegerField()),
                (
                    "processed_end_hz",
                    models.BigIntegerField(
                        help_text="Exclusive upper edge: the range is [start, end)."
                    ),
                ),
                (
                    "processed_rf",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Func(
                            models.F("processed_start_hz"),
                            models.F("processed_end_hz"),
                            models.Value("[)"),
                            function="int8range",
                            output_field=django.contrib.postgres.fields.ranges.BigIntegerRangeField(),
                        ),
                        output_field=django.contrib.postgres.fields.ranges.BigIntegerRangeField(),
                    ),
                ),
                ("channel_bandwidth_hz", models.BigIntegerField(blank=True, null=True)),
                (
                    "decimation_factor",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "active_period",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Func(
                            models.F("effective_from"),
                            models.F("effective_until"),
                            models.Value("[)"),
                            function="tstzrange",
                            output_field=django.contrib.postgres.fields.ranges.DateTimeRangeField(),
                        ),
                        output_field=django.contrib.postgres.fields.ranges.DateTimeRangeField(),
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decimator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="inventory.decimator",
                    ),
                ),
                (
                    "payload_path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decimator_assignments",
                        to="inventory.payloadpath",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "decimator_assignment",
                "ordering": ["decimator__code", "-effective_from"],
                "default_permissions": ("view",),
            },
        ),
        migrations.AddConstraint(
            model_name="decimator",
            constraint=models.UniqueConstraint(
                fields=("hub", "code"), name="uq_decimator_hub_code"
            ),
        ),
        migrations.AddIndex(
            model_name="decimatorassignment",
            index=models.Index(
                condition=models.Q(("is_active", True)),
                fields=["decimator", "effective_from"],
                name="decimator_assignment_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="decimatorassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("processed_start_hz__lt", models.F("processed_end_hz"))
                ),
                name="ck_decimator_assignment_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="decimatorassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_until__isnull", True),
                    ("effective_until__gt", models.F("effective_from")),
                    _connector="OR",
                ),
                name="ck_decimator_assignment_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="decimatorassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("channel_bandwidth_hz__isnull", True),
                    ("channel_bandwidth_hz__gt", 0),
                    _connector="OR",
                ),
                name="ck_decimator_assignment_bandwidth",
            ),
        ),
        migrations.AddConstraint(
            model_name="decimatorassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("decimation_factor__isnull", True),
                    ("decimation_factor__gt", 0),
                    _connector="OR",
                ),
                name="ck_decimator_assignment_factor",
            ),
        ),
        migrations.AddConstraint(
            model_name="decimatorassignment",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("is_active", True)),
                expressions=[("decimator", "="), ("active_period", "&&")],
                name="excl_decimator_assignment_overlap",
            ),
        ),
    ]
