# Generated by Django 5.2.16 on 2026-08-04 20:01

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("beams", "0003_assignment_window_composite_key"),
        (
            "inventory",
            "0004_spectrumresource_frequencywindow_uq_window_id_edges_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SpectrumReservation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("record_version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("assignment_start_hz", models.BigIntegerField()),
                ("assignment_end_hz", models.BigIntegerField()),
                (
                    "leg",
                    models.CharField(
                        choices=[
                            ("HUB_UPLINK", "Hub uplink"),
                            ("REMOTE_DOWNLINK", "Remote downlink"),
                            ("REMOTE_UPLINK", "Remote uplink"),
                            ("HUB_DOWNLINK", "Hub downlink"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "polarization",
                    models.CharField(
                        choices=[
                            ("RHCP", "Right-hand circular"),
                            ("LHCP", "Left-hand circular"),
                            ("H", "Linear horizontal"),
                            ("V", "Linear vertical"),
                        ],
                        max_length=4,
                    ),
                ),
                ("occupied_start_hz", models.BigIntegerField()),
                ("occupied_end_hz", models.BigIntegerField()),
                ("allocated_start_hz", models.BigIntegerField()),
                ("allocated_end_hz", models.BigIntegerField()),
                (
                    "occupied_rf",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Func(
                            models.F("occupied_start_hz"),
                            models.F("occupied_end_hz"),
                            models.Value("[)"),
                            function="int8range",
                            output_field=django.contrib.postgres.fields.ranges.BigIntegerRangeField(),
                        ),
                        output_field=django.contrib.postgres.fields.ranges.BigIntegerRangeField(),
                    ),
                ),
                (
                    "allocated_rf",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Func(
                            models.F("allocated_start_hz"),
                            models.F("allocated_end_hz"),
                            models.Value("[)"),
                            function="int8range",
                            output_field=django.contrib.postgres.fields.ranges.BigIntegerRangeField(),
                        ),
                        output_field=django.contrib.postgres.fields.ranges.BigIntegerRangeField(),
                    ),
                ),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                (
                    "active_period",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Func(
                            models.F("valid_from"),
                            models.F("valid_until"),
                            models.Value("[)"),
                            function="tstzrange",
                            output_field=django.contrib.postgres.fields.ranges.DateTimeRangeField(),
                        ),
                        output_field=django.contrib.postgres.fields.ranges.DateTimeRangeField(),
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("SATNET_PATH", "Held by a Satnet Path"),
                            ("FIXED_RESERVE", "Fixed reserved area"),
                        ],
                        default="SATNET_PATH",
                        max_length=16,
                    ),
                ),
                (
                    "satnet_path_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "direction",
                    models.CharField(
                        blank=True,
                        choices=[("FWD", "Forward"), ("RTN", "Return")],
                        max_length=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PLANNED", "Planned"),
                            ("PENDING_APPROVAL", "Pending approval"),
                            ("ON_AIR", "On air"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("RETIRED", "Retired"),
                            ("IMPORT_REVIEW", "Awaiting import review"),
                        ],
                        max_length=16,
                    ),
                ),
                ("reserves_spectrum", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "beam_spectrum_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="beams.beamspectrumassignment",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "spectrum_resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="inventory.spectrumresource",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "spectrum_reservation",
                "ordering": ["spectrum_resource__code", "allocated_start_hz"],
                "default_permissions": ("view",),
                "indexes": [
                    models.Index(
                        condition=models.Q(("reserves_spectrum", True)),
                        fields=["beam_spectrum_assignment", "allocated_start_hz"],
                        name="reservation_capacity_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("allocated_start_hz__lt", models.F("allocated_end_hz"))
                        ),
                        name="ck_res_alloc_start_lt_end",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("occupied_start_hz__lt", models.F("occupied_end_hz"))
                        ),
                        name="ck_res_occ_start_lt_end",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("occupied_start_hz__gte", models.F("allocated_start_hz")),
                            ("occupied_end_hz__lte", models.F("allocated_end_hz")),
                        ),
                        name="ck_res_occ_in_alloc",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "allocated_start_hz__gte",
                                models.F("assignment_start_hz"),
                            ),
                            ("allocated_end_hz__lte", models.F("assignment_end_hz")),
                        ),
                        name="ck_res_within_assignment",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("valid_until__isnull", True),
                            ("valid_until__gt", models.F("valid_from")),
                            _connector="OR",
                        ),
                        name="ck_res_period",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("kind", "SATNET_PATH"),
                                ("satnet_path_id__isnull", False),
                                models.Q(("status", ""), _negated=True),
                            ),
                            models.Q(
                                ("direction", ""),
                                ("kind", "FIXED_RESERVE"),
                                ("satnet_path_id__isnull", True),
                                ("status", ""),
                            ),
                            _connector="OR",
                        ),
                        name="ck_res_kind_path",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("reserves_spectrum", True),
                                (
                                    "status__in",
                                    ("PLANNED", "PENDING_APPROVAL", "ON_AIR"),
                                ),
                            ),
                            models.Q(
                                ("reserves_spectrum", False),
                                (
                                    "status__in",
                                    ("DRAFT", "CANCELLED", "RETIRED", "IMPORT_REVIEW"),
                                ),
                            ),
                            ("status", "SUSPENDED"),
                            ("status", ""),
                            _connector="OR",
                        ),
                        name="ck_res_reserves_status",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("direction", "FWD"),
                                ("leg__in", ["HUB_UPLINK", "REMOTE_DOWNLINK"]),
                            ),
                            models.Q(
                                ("direction", "RTN"),
                                ("leg__in", ["REMOTE_UPLINK", "HUB_DOWNLINK"]),
                            ),
                            ("direction", ""),
                            _connector="OR",
                        ),
                        name="ck_res_direction_leg",
                    ),
                    django.contrib.postgres.constraints.ExclusionConstraint(
                        condition=models.Q(("reserves_spectrum", True)),
                        expressions=[
                            ("spectrum_resource", "="),
                            ("allocated_rf", "&&"),
                            ("active_period", "&&"),
                        ],
                        name="excl_reservation_overlap",
                    ),
                ],
            },
        ),
    ]
