# Generated by Django 5.2.16 on 2026-08-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExportPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Export policy",
                "permissions": [("export_data", "Can export data")],
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
