# Generated by Django 5.2.16 on 2026-08-08 10:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imports_exports", "0001_export_capability"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_sha256", models.CharField(max_length=64)),
                ("file_size", models.BigIntegerField(default=0)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("DRY_RUN", "Dry run"),
                            ("COMMITTED", "Committed"),
                            ("FAILED", "Failed"),
                        ],
                        default="DRY_RUN",
                        max_length=16,
                    ),
                ),
                (
                    "batch_policy",
                    models.CharField(
                        choices=[
                            ("ALL_OR_NOTHING", "All or nothing"),
                            ("ROW_BY_ROW", "Row by row"),
                        ],
                        default="ALL_OR_NOTHING",
                        max_length=16,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("committed_at", models.DateTimeField(blank=True, null=True)),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("counts", models.JSONField(blank=True, default=dict)),
                ("change_reason", models.TextField(blank=True)),
                ("message", models.TextField(blank=True)),
                (
                    "committed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="committed_import_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "import_batch",
                "ordering": ["-uploaded_at"],
                "permissions": [
                    ("run_import_dryrun", "Can upload a file and see what it would do"),
                    ("commit_import", "Can commit a reviewed import batch"),
                ],
                "default_permissions": ("view",),
            },
        ),
        migrations.CreateModel(
            name="ImportMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("kind", models.CharField(max_length=40)),
                ("label", models.CharField(max_length=255)),
                ("target_id", models.UUIDField()),
                ("target_repr", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_mappings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "import_mapping",
                "ordering": ["kind", "label"],
                "default_permissions": ("view",),
            },
        ),
        migrations.CreateModel(
            name="ImportRow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sheet", models.CharField(max_length=100)),
                ("row_number", models.PositiveIntegerField()),
                ("raw", models.JSONField(blank=True, default=dict)),
                ("normalized", models.JSONField(blank=True, default=dict)),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("IGNORED_FREE_CAPACITY", "Ignored — free capacity"),
                            ("ERROR", "Error"),
                            ("NEEDS_MAPPING", "Needs mapping"),
                            ("DUPLICATE", "Duplicate"),
                            ("CONFLICT", "Conflict"),
                            ("WARNING", "Warning"),
                            ("VALID", "Valid"),
                        ],
                        max_length=24,
                    ),
                ),
                ("messages", models.JSONField(blank=True, default=list)),
                ("resulting_object_id", models.UUIDField(blank=True, null=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="imports_exports.importbatch",
                    ),
                ),
            ],
            options={
                "db_table": "import_row",
                "ordering": ["sheet", "row_number"],
                "default_permissions": ("view",),
            },
        ),
        migrations.AddIndex(
            model_name="importbatch",
            index=models.Index(
                fields=["stage", "-uploaded_at"], name="import_batch_stage_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importbatch",
            index=models.Index(fields=["file_sha256"], name="import_batch_sha_idx"),
        ),
        migrations.AddConstraint(
            model_name="importmapping",
            constraint=models.UniqueConstraint(
                fields=("kind", "label"), name="uq_import_mapping_label"
            ),
        ),
        migrations.AddIndex(
            model_name="importrow",
            index=models.Index(
                fields=["batch", "classification"], name="import_row_class_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="importrow",
            constraint=models.UniqueConstraint(
                fields=("batch", "sheet", "row_number"), name="uq_import_row_position"
            ),
        ),
    ]
