# Generated by Django 5.2.16 on 2026-08-03 08:51

import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("occurred_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("actor_username", models.CharField(blank=True, max_length=150)),
                (
                    "action",
                    models.CharField(
                        help_text="Stable action code, e.g. USER_LOGGED_IN.",
                        max_length=64,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[("SUCCESS", "Success"), ("FAILURE", "Failure")],
                        max_length=8,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                (
                    "object_type",
                    models.CharField(
                        blank=True,
                        help_text="app_label.ModelName of the affected object.",
                        max_length=100,
                    ),
                ),
                ("object_id", models.UUIDField(blank=True, null=True)),
                ("object_repr", models.CharField(blank=True, max_length=255)),
                ("before", models.JSONField(blank=True, null=True)),
                ("after", models.JSONField(blank=True, null=True)),
                ("change_reason", models.TextField(blank=True)),
                ("request_id", models.UUIDField(blank=True, null=True)),
                ("source_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=512)),
                ("import_batch_id", models.UUIDField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null for anonymous or system-initiated actions.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit event",
                "verbose_name_plural": "Audit events",
                "db_table": "audit_event",
                "ordering": ["-occurred_at"],
                "permissions": [
                    ("view_auditevent", "Can view their own audit events"),
                    ("view_all_auditevent", "Can view all audit events"),
                ],
                "default_permissions": (),
                "indexes": [
                    models.Index(
                        fields=["-occurred_at"], name="audit_occurred_desc_idx"
                    ),
                    models.Index(
                        fields=["object_type", "object_id", "-occurred_at"],
                        name="audit_object_history_idx",
                    ),
                    models.Index(
                        fields=["actor", "-occurred_at"], name="audit_actor_idx"
                    ),
                    models.Index(
                        fields=["action", "-occurred_at"], name="audit_action_idx"
                    ),
                    models.Index(
                        condition=models.Q(("outcome", "FAILURE")),
                        fields=["-occurred_at"],
                        name="audit_failures_idx",
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["before"], name="audit_before_gin_idx"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["after"], name="audit_after_gin_idx"
                    ),
                ],
            },
        ),
    ]
