# Generated by Django 5.2.16 on 2026-08-04 20:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("beams", "0003_assignment_window_composite_key"),
        (
            "inventory",
            "0004_spectrumresource_frequencywindow_uq_window_id_edges_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Satnet",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("record_version", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("effective_from", models.DateTimeField()),
                (
                    "effective_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leave empty for an open-ended record.",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=200)),
                ("service_type", models.CharField(blank=True, max_length=100)),
                ("customer", models.CharField(blank=True, max_length=200)),
                ("platform", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("technical_notes", models.TextField(blank=True)),
                (
                    "beam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="satnets",
                        to="beams.beam",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "default_guard_policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="satnets",
                        to="inventory.guardpolicy",
                    ),
                ),
                (
                    "gateway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="satnets",
                        to="inventory.gateway",
                    ),
                ),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="satnets",
                        to="inventory.hub",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "satnet",
                "ordering": ["beam__code", "code"],
                "permissions": [
                    ("manage_satnets", "Can create, edit and deactivate Satnets")
                ],
                "default_permissions": ("view",),
                "indexes": [
                    models.Index(
                        condition=models.Q(("is_active", True)),
                        fields=["beam", "hub"],
                        name="satnet_scope_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("beam", "code"), name="uq_satnet_beam_code"
                    ),
                    models.UniqueConstraint(
                        fields=("id", "beam"), name="uq_satnet_id_beam"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("effective_until__isnull", True),
                            ("effective_until__gt", models.F("effective_from")),
                            _connector="OR",
                        ),
                        name="ck_satnet_effective_period",
                    ),
                ],
            },
        ),
    ]
