# Generated by Django 5.2.16 on 2026-08-04 09:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0003_payload_path_composite_keys"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Beam",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("record_version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "coverage",
                    models.CharField(
                        blank=True,
                        help_text="Coverage area or spot name.",
                        max_length=200,
                    ),
                ),
                (
                    "configuration_state",
                    models.CharField(
                        choices=[
                            (
                                "INCOMPLETE",
                                "Incomplete — not every enabled direction is configured",
                            ),
                            ("INVALID", "Invalid — configured, but a rule is broken"),
                            ("VALID", "Valid — every enabled direction passes"),
                        ],
                        default="INCOMPLETE",
                        max_length=12,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("engineering_reference", models.TextField(blank=True)),
                (
                    "activated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "band",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="beams",
                        to="inventory.band",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "satellite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="beams",
                        to="inventory.satellite",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "beam",
                "ordering": ["code"],
                "permissions": [("manage_beams", "Can configure and activate Beams")],
                "default_permissions": ("view",),
            },
        ),
        migrations.CreateModel(
            name="BeamDirectionConfig",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("record_version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("FWD", "Forward"), ("RTN", "Return")], max_length=3
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="A disabled direction is a deliberate configuration, not an omission.",
                    ),
                ),
                (
                    "canonical_leg",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("HUB_UPLINK", "Hub uplink"),
                            ("REMOTE_DOWNLINK", "Remote downlink"),
                            ("REMOTE_UPLINK", "Remote uplink"),
                            ("HUB_DOWNLINK", "Hub downlink"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "uplink_polarization",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RHCP", "Right-hand circular"),
                            ("LHCP", "Left-hand circular"),
                            ("H", "Linear horizontal"),
                            ("V", "Linear vertical"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "downlink_polarization",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RHCP", "Right-hand circular"),
                            ("LHCP", "Left-hand circular"),
                            ("H", "Linear horizontal"),
                            ("V", "Linear vertical"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "spectral_inversion_override",
                    models.BooleanField(blank=True, null=True),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "beam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="direction_configs",
                        to="beams.beam",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "downlink_window",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="beam_configs_as_downlink",
                        to="inventory.frequencywindow",
                    ),
                ),
                (
                    "payload_path",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="beam_direction_configs",
                        to="inventory.payloadpath",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uplink_window",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="beam_configs_as_uplink",
                        to="inventory.frequencywindow",
                    ),
                ),
            ],
            options={
                "db_table": "beam_direction_config",
                "ordering": ["beam__code", "direction"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="BeamDirectionEquipmentProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Lower sorts first when several profiles remain valid.",
                    ),
                ),
                (
                    "direction_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_profiles",
                        to="beams.beamdirectionconfig",
                    ),
                ),
                (
                    "equipment_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="beam_directions",
                        to="inventory.equipmentprofile",
                    ),
                ),
            ],
            options={
                "db_table": "beam_direction_equipment_profile",
                "ordering": ["priority", "equipment_profile__code"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="BeamValidationResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ran_at", models.DateTimeField(auto_now_add=True)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("PASSED", "Passed"),
                            ("PASSED_WITH_WARNINGS", "Passed with warnings"),
                            ("FAILED", "Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "configuration_state",
                    models.CharField(
                        choices=[
                            (
                                "INCOMPLETE",
                                "Incomplete — not every enabled direction is configured",
                            ),
                            ("INVALID", "Invalid — configured, but a rule is broken"),
                            ("VALID", "Valid — every enabled direction passes"),
                        ],
                        max_length=12,
                    ),
                ),
                ("findings", models.JSONField(default=list)),
                ("activated", models.BooleanField(default=False)),
                (
                    "beam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_results",
                        to="beams.beam",
                    ),
                ),
                (
                    "ran_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "beam_validation_result",
                "ordering": ["-ran_at"],
                "default_permissions": (),
            },
        ),
        migrations.AddConstraint(
            model_name="beam",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_active", False),
                    models.Q(
                        ("activated_at__isnull", False), ("activated_by__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="ck_beam_active_has_activation_record",
            ),
        ),
        migrations.AddConstraint(
            model_name="beam",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_active", False),
                    ("configuration_state", "VALID"),
                    _connector="OR",
                ),
                name="ck_beam_active_requires_valid_configuration",
            ),
        ),
        migrations.AddConstraint(
            model_name="beamdirectionconfig",
            constraint=models.UniqueConstraint(
                fields=("beam", "direction"), name="uq_beam_direction"
            ),
        ),
        migrations.AddConstraint(
            model_name="beamdirectionconfig",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("downlink_window__isnull", True),
                        ("payload_path__isnull", True),
                        ("uplink_window__isnull", True),
                    ),
                    models.Q(
                        ("downlink_window__isnull", False),
                        ("payload_path__isnull", False),
                        ("uplink_window__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="ck_beam_direction_chain_all_or_nothing",
            ),
        ),
        migrations.AddConstraint(
            model_name="beamdirectionequipmentprofile",
            constraint=models.UniqueConstraint(
                fields=("direction_config", "equipment_profile"),
                name="uq_beam_direction_equipment",
            ),
        ),
        migrations.AddIndex(
            model_name="beamvalidationresult",
            index=models.Index(
                fields=["beam", "-ran_at"], name="beam_validation_recent_idx"
            ),
        ),
    ]
