# Generated by Django 5.2.16 on 2026-08-04 17:03

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beams", "0001_initial"),
        (
            "inventory",
            "0004_spectrumresource_frequencywindow_uq_window_id_edges_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BeamDirectionSpectrumResource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "direction_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spectrum_resources",
                        to="beams.beamdirectionconfig",
                    ),
                ),
                (
                    "spectrum_resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="beam_directions",
                        to="inventory.spectrumresource",
                    ),
                ),
            ],
            options={
                "db_table": "beam_direction_spectrum_resource",
                "ordering": ["spectrum_resource__leg", "spectrum_resource__code"],
                "default_permissions": (),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("direction_config", "spectrum_resource"),
                        name="uq_beam_direction_spectrum_resource",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BeamSpectrumAssignment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("record_version", models.PositiveIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rf_start_hz", models.BigIntegerField()),
                (
                    "rf_end_hz",
                    models.BigIntegerField(
                        help_text="Exclusive upper edge: the range is [start, end)."
                    ),
                ),
                ("window_rf_start_hz", models.BigIntegerField()),
                ("window_rf_end_hz", models.BigIntegerField()),
                (
                    "rf_range",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Func(
                            models.F("rf_start_hz"),
                            models.F("rf_end_hz"),
                            models.Value("[)"),
                            function="int8range",
                            output_field=django.contrib.postgres.fields.ranges.BigIntegerRangeField(),
                        ),
                        output_field=django.contrib.postgres.fields.ranges.BigIntegerRangeField(),
                    ),
                ),
                ("effective_from", models.DateTimeField()),
                (
                    "effective_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leave empty for an open-ended assignment.",
                        null=True,
                    ),
                ),
                (
                    "effective_period",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Func(
                            models.F("effective_from"),
                            models.F("effective_until"),
                            models.Value("[)"),
                            function="tstzrange",
                            output_field=django.contrib.postgres.fields.ranges.DateTimeRangeField(),
                        ),
                        output_field=django.contrib.postgres.fields.ranges.DateTimeRangeField(),
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "direction_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spectrum_assignments",
                        to="beams.beamdirectionconfig",
                    ),
                ),
                (
                    "frequency_window",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="beam_assignments",
                        to="inventory.frequencywindow",
                    ),
                ),
                (
                    "payload_path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="beam_assignments",
                        to="inventory.payloadpath",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "beam_spectrum_assignment",
                "ordering": ["direction_config__beam__code", "rf_start_hz"],
                "default_permissions": (),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("rf_start_hz__lt", models.F("rf_end_hz"))),
                        name="ck_assignment_start_lt_end",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("effective_until__isnull", True),
                            ("effective_until__gt", models.F("effective_from")),
                            _connector="OR",
                        ),
                        name="ck_assignment_effective_period",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("rf_start_hz__gte", models.F("window_rf_start_hz")),
                            ("rf_end_hz__lte", models.F("window_rf_end_hz")),
                        ),
                        name="ck_assignment_within_window",
                    ),
                    django.contrib.postgres.constraints.ExclusionConstraint(
                        condition=models.Q(("is_active", True)),
                        expressions=[
                            ("direction_config", "="),
                            ("frequency_window", "="),
                            ("rf_range", "&&"),
                            ("effective_period", "&&"),
                        ],
                        name="excl_assignment_overlap",
                    ),
                ],
            },
        ),
    ]
