# Generated by Django 5.2.16 on 2026-08-04 22:37

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beams", "0003_assignment_window_composite_key"),
        (
            "inventory",
            "0004_spectrumresource_frequencywindow_uq_window_id_edges_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="beam",
            name="effective_from",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="beam",
            name="effective_until",
            field=models.DateTimeField(
                blank=True, help_text="Leave empty for an open-ended Beam.", null=True
            ),
        ),
        migrations.AddConstraint(
            model_name="beam",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_until__isnull", True),
                    ("effective_until__gt", models.F("effective_from")),
                    _connector="OR",
                ),
                name="ck_beam_effective_period",
            ),
        ),
    ]
