# Generated by Django 5.2.16 on 2026-08-05 08:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("satnet_paths", "0004_lifecycle_capabilities"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[("APPROVED", "Approved"), ("REJECTED", "Rejected")],
                        max_length=8,
                    ),
                ),
                ("decided_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("comment", models.TextField(blank=True)),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PLANNED", "Planned"),
                            ("PENDING_APPROVAL", "Pending approval"),
                            ("ON_AIR", "On air"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("RETIRED", "Retired"),
                            ("IMPORT_REVIEW", "Awaiting import review"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PLANNED", "Planned"),
                            ("PENDING_APPROVAL", "Pending approval"),
                            ("ON_AIR", "On air"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("RETIRED", "Retired"),
                            ("IMPORT_REVIEW", "Awaiting import review"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "satnet_path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_decisions",
                        to="satnet_paths.satnetpath",
                    ),
                ),
            ],
            options={
                "db_table": "approval_decision",
                "ordering": ["-decided_at"],
                "default_permissions": ("view",),
                "indexes": [
                    models.Index(
                        fields=["satnet_path", "-decided_at"], name="approval_path_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("decision", "APPROVED"),
                                ("from_status", "PENDING_APPROVAL"),
                                ("to_status", "ON_AIR"),
                            ),
                            models.Q(
                                ("decision", "REJECTED"),
                                ("from_status", "PENDING_APPROVAL"),
                                ("to_status", "PLANNED"),
                            ),
                            _connector="OR",
                        ),
                        name="ck_approval_decision_transition",
                    )
                ],
            },
        ),
    ]
