"""Generate the S0 RF confirmation intake package from the models. Section 24.

``docs/design/05`` requires each intake workbook to carry *"the exact columns the eventual
import expects"*. Generating them is the only way that stays true: a hand-maintained
column list is correct on the day it is written and silently wrong after the next
migration, and the cost lands on whoever has already entered four hundred rows under the
old headings.

Run it after any change to the inventory models, and commit the result::

    python manage.py export_intake_templates

``tests/rf_confirmation`` fails if the committed files differ from what this produces, so
the drift is caught in CI rather than by an RF engineer.
"""

from __future__ import annotations

import csv
import io
import json
from pathlib import Path
from typing import Any

from django.conf import settings
from django.core.management.base import BaseCommand

from inventory import intake

#: Written relative to the repository root so the package sits with the documents that
#: explain it, not with the code that produced it.
PACKAGE_DIR = Path("docs/rf-confirmation")
TEMPLATE_DIR = PACKAGE_DIR / "templates"
GUIDE_FILE = PACKAGE_DIR / "column-guide.md"
GOLDEN_FILE = TEMPLATE_DIR / "golden-example.template.json"

GENERATED_NOTICE = (
    "<!-- Generated by `python manage.py export_intake_templates`. Do not edit by hand: "
    "the columns are read from the models, and a manual edit will be reverted by the next "
    "run and reported by tests/rf_confirmation. -->"
)

#: The shape ``tests/domain/test_golden_examples.py`` reads. Every value is empty: §26.20
#: forbids shipping a plausible worked example, and a template with numbers in it is one
#: copy-and-paste away from becoming a fixture nobody can trace.
#:
#: Widened by the **OQ-22** answer (**A-29**), which asks the example to state considerably
#: more than the bandwidth arithmetic: the Payload Path Window, the Beam Spectrum Assignment,
#: the RF/IF conversion rule, the equipment limits, the validity periods, the requested
#: allocation, the expected free capacity — and three outcomes that exercise the reuse model
#: end to end. The empty ``scenarios`` entry is a shape, not an example: a file that leaves it
#: as it ships fails the completeness check rather than closing the question quietly.
GOLDEN_EXAMPLE_TEMPLATE: dict[str, Any] = {
    "name": "",
    "source": "",
    "direction": "",
    "payload_path_window": {
        "uplink": [None, None],
        "uplink_polarization": "",
        "downlink": [None, None],
        "downlink_polarization": "",
    },
    "beam_spectrum_assignment": {
        "uplink": [None, None],
        "downlink": [None, None],
        "effective_from": "",
        "effective_until": None,
    },
    "equipment": {
        "conversion_method": "",
        "sideband": "",
        "lo_hz": None,
        "if_min_hz": None,
        "if_max_hz": None,
    },
    "validity": {"valid_from": "", "valid_until": None},
    "symbol_rate_sps": None,
    "occupied_bandwidth_hz": None,
    "rolloff": "",
    "uplink_centre_hz": None,
    "guard": {
        "mode": "",
        "left_hz": None,
        "right_hz": None,
        "percent_left": None,
        "percent_right": None,
    },
    "translation": {"method": "", "constant_hz": None, "spectral_inversion": False},
    #: Only needed by an ACCEPT_INDEPENDENT_POLARIZATION scenario: the windows of the
    #: orthogonal polarization whose RF chains the site implements separately (**A-21**).
    "independent_polarization": {
        "polarization": "",
        "uplink": [None, None],
        "downlink": [None, None],
    },
    "expect": {
        "occupied_bandwidth_hz": None,
        "uplink_occupied": [None, None],
        "uplink_allocated": [None, None],
        "downlink_occupied": [None, None],
        "downlink_allocated": [None, None],
        "if_occupied": [None, None],
        "free_capacity": {"leg": "", "gaps": [], "total_free_hz": None},
        "scenarios": [
            {
                "name": "",
                "kind": "",
                "uplink_centre_hz": None,
                "valid_from": None,
                "valid_until": None,
                "expect": "",
                "expect_finding": "",
            }
        ],
    },
}


def sheet_csv(sheet: intake.Sheet) -> str:
    """One header row and no data rows.

    A single header row is not an aesthetic choice: it is what the S15 importer will parse.
    Units and permitted values go in the column guide, where a person reads them, rather
    than in extra rows an importer would have to learn to skip.
    """
    buffer = io.StringIO(newline="")
    # Excel is the tool these will be opened in, and it treats a bare LF inside a quoted
    # field as a row break. csv's own dialect handles the quoting; the newline is pinned
    # here so the file is identical on every platform that regenerates it.
    writer = csv.writer(buffer, lineterminator="\r\n")
    writer.writerow([column.heading for column in sheet.columns])
    return buffer.getvalue()


def _read_verbatim(path: Path) -> str:
    """Read a file without translating its line endings.

    ``Path.read_text`` only grew a ``newline`` argument in 3.13, and this project runs 3.12.
    """
    with path.open(encoding="utf-8", newline="") as handle:
        return handle.read()


def _cell(text: str) -> str:
    """Make a value safe to put in a Markdown table cell.

    A pipe would end the cell and shift every column after it, and a newline would end the
    row. Both are reachable from model ``help_text``, which is written for a form field and
    knows nothing about where else it is rendered.
    """
    return " ".join(text.split()).replace("|", r"\|")


def _column_rows(sheet: intake.Sheet) -> list[tuple[str, str, str, str, str]]:
    rows: list[tuple[str, str, str, str, str]] = []
    for column in sheet.columns:
        if column.field:
            model_field = sheet.model._meta.get_field(column.field)
            unit = intake.unit_of(model_field)  # type: ignore[arg-type]
            required = "yes" if intake.is_required(model_field) else "no"  # type: ignore[arg-type]
            allowed = intake.allowed_values_of(model_field)  # type: ignore[arg-type]
            note = column.note or str(getattr(model_field, "help_text", "") or "")
        elif column.lookup:
            model_field = sheet.model._meta.get_field(column.lookup)
            target = model_field.related_model
            unit = f"code of an existing {target._meta.verbose_name}"  # type: ignore[union-attr]
            required = "yes" if intake.is_required(model_field) else "no"  # type: ignore[arg-type]
            allowed = ""
            note = column.note
        else:
            unit = "text"
            required = "no"
            allowed = ""
            note = column.note
        rows.append((column.heading, unit, required, allowed, note))
    return rows


def guide_markdown() -> str:
    """The human half of the package: what each column means and what may go in it."""
    parts: list[str] = [
        "# Intake column guide",
        "",
        GENERATED_NOTICE,
        "",
        "One section per sheet in `templates/`. The CSV files carry a single header row so "
        "the S15 importer can read them directly; everything a person needs in order to "
        "fill one in is here.",
        "",
        "**Leave a cell empty when the answer is unconfirmed.** An empty cell is a recorded "
        "gap. A guessed value is indistinguishable from a confirmed one the moment it is "
        "loaded, which is what acceptance criterion §26.20 exists to prevent.",
        "",
    ]
    for sheet in intake.SHEETS:
        parts += [
            f"## {sheet.title} — `templates/{sheet.filename}`",
            "",
            f"**Answers:** {', '.join(sheet.open_questions)}",
            "",
            sheet.purpose,
            "",
            "| Column | Value | Required | Permitted values | Notes |",
            "|---|---|---|---|---|",
        ]
        for heading, unit, required, allowed, note in _column_rows(sheet):
            allowed_cell = f"`{_cell(allowed)}`" if allowed else "—"
            note_cell = _cell(note) if note else "—"
            parts.append(
                f"| `{heading}` | {_cell(unit)} | {required} | {allowed_cell} | {note_cell} |"
            )
        parts.append("")
        if sheet.supplied_by_the_platform:
            parts += [
                "**Not collected, and deliberately so:**",
                "",
            ]
            for name, reason in sheet.supplied_by_the_platform.items():
                parts.append(f"- `{name}` — {reason}")
            parts.append("")
    return "\n".join(parts)


class Command(BaseCommand):
    help = "Regenerate the RF confirmation intake templates and column guide."

    def add_arguments(self, parser: Any) -> None:
        parser.add_argument(
            "--check",
            action="store_true",
            help="Report whether the committed package is up to date, writing nothing.",
        )

    def handle(self, *args: Any, **options: Any) -> None:
        root = Path(settings.BASE_DIR)
        stale: list[Path] = []

        for path, content in self._generated(root).items():
            if options["check"]:
                # Read with newline="" so the CRLF the sheets are written with survives.
                # Without it Python translates line endings on the way in and every CSV
                # reports as stale, which would make --check useless in exactly the mode
                # somebody would trust it in.
                current = _read_verbatim(path) if path.exists() else None
                if current != content:
                    stale.append(path.relative_to(root))
                continue
            path.parent.mkdir(parents=True, exist_ok=True)
            # newline="" so csv's own \r\n survives; Python would otherwise translate it.
            path.write_text(content, encoding="utf-8", newline="")
            self.stdout.write(f"  wrote {path.relative_to(root)}")

        if options["check"]:
            if stale:
                listed = "\n".join(f"  {path}" for path in stale)
                self.stderr.write(
                    "The intake package is out of date with the models:\n"
                    f"{listed}\n"
                    "Run: python manage.py export_intake_templates"
                )
                raise SystemExit(1)
            self.stdout.write(self.style.SUCCESS("Intake package is up to date."))
            return

        self.stdout.write(
            self.style.SUCCESS(f"Regenerated {len(intake.SHEETS)} intake sheets and the guide.")
        )

    def _generated(self, root: Path) -> dict[Path, str]:
        files: dict[Path, str] = {
            root / TEMPLATE_DIR / sheet.filename: sheet_csv(sheet) for sheet in intake.SHEETS
        }
        files[root / GUIDE_FILE] = guide_markdown()
        files[root / GOLDEN_FILE] = (
            json.dumps(GOLDEN_EXAMPLE_TEMPLATE, indent=2, ensure_ascii=False) + "\n"
        )
        return files
